### ISSUE TITLE
Structured data is inserted in another existing script tags

### ISSUE THREAD

**Issue by ivanhercaz** [pelican-plugins/seo#19]
Hi!
I am using this plugin in one of my websites and the Google Console reported me an error related with the structured data based on Schema. At the first time I thought it may be related with this note in the README:

> Note that schemas generated by default are compliant with Schema.org but not (by default) Google-compliant.

However, after check the console and then the HTML files generated I discovered that structured data is being added in existing `<script>` tags and then it creates two new `<script type="application/ld+json">` but let them empty. So in my `<head>` I have:

```html
  <script src="/theme/navbar.js">
   {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "name": "Coruja Digital", "item": "https://corujadigital.tech"}, {"@type": "ListItem", "position": 2, "name": "Blog", "item": "https://corujadigital.tech/blog"}, {"@type": "ListItem", "position": 3, "name": "Rediseno sitio web", "item": "https://corujadigital.tech/blog/rediseno-sitio-web.html"}]}
  </script>
  <script src="/theme/js/fontawesome-all.min.js">
   {"@context": "https://schema.org", "@type": "Article", "author": {"@type": "Person", "name": "Iván Hernández Cazorla"}, "publisher": {"@type": "Organization", "name": "Coruja Digital", "logo": {"@type": "ImageObject", "url": "https://corujadigital.tech/theme/logo_coruja_digital.png"}}, "headline": "Rediseño del sitio web de Coruja Digital", "about": "corujadigital.tech", "datePublished": "2020-10-29 00:00"}
  </script>
  <script type="application/ld+json">
  </script>
  <script type="application/ld+json">
  </script>
```

I upgraded to the latest version (1.0.1) but it did not fix this. Have you got any idea of what could be happening?

Thanks in advance!

**Comment by MaevaBrunelles** [comment]
Hi @ivanhercaz,

Thanks for your interest on this plugin!
If your site is hosted on GitHub, can you please pointed it to me? Or at least send me the Markdown of your concerned article. I need to reproduce this case to dig.

**Comment by ivanhercaz** [comment]
Thanks to you for your work on this plugin!

[My site has a GitHub repository](https://github.com/Coruja-Digital/corujadigital.tech/) and then I deploy it with Netlify. If I can help with something, just notice me!

**Comment by MaevaBrunelles** [comment]
I had a lot of fun with this issue, I facepalmed myself seeing the code I've written 2 years ago 😅Anyway, I pushed a commit which fix this bug. Before I merge it, can you clone the branch, generate your site and tell me if it works as you expect?

**Comment by ivanhercaz** [comment]
Thank you very much, @MaevaBrunelles! Very fast and it works really nice. I uninstalled the package and then installed it with `pip` using your branch. Your fix works! I am happy you enjoy this issue.

**Comment by MaevaBrunelles** [comment]
@ivanhercaz you can now pip install the `1.0.2` version, which fix this issue. Thanks for raising it!
