### ISSUE TITLE
Ensure all plugin settings are SEO_* prefixed

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/seo#3]
For example, the following settings should probably be prefixed with `SEO_[…]` in order to prevent potential collisions with other plugins.

```python
ARTICLES_LIMIT = 10
PAGES_LIMIT = 10
```

**Comment by MaevaBrunelles** [comment]
Good idea, currently there is only this two settings to update.
I didn't create the PR yet because the linter action raise an error:
```
Run invoke lint
ERROR: /home/runner/work/seo/seo/pelican/plugins/seo/seo.py Imports are incorrectly sorted.
##[error]Process completed with exit code 1.
```

But if i do it locally, everything seems good:
```
invoke lint
All done! ✨ 🍰 ✨
28 files would be left unchanged.
```

Any idea of what I'm missing?

**Comment by justinmayer** [comment]
I think this was caused by inconsistent behavior between running the `isort` executable manually and running its Pre-commit hook. I believe this annoying behavior inconsistency was resolved in `isort` v5, to which I just updated via: https://github.com/pelican-plugins/seo/commit/1a2f8744b3ad7ce4ccbb5b1f0b980e4dc21b98cd

In short, perhaps try again on current master and see if the problem you mentioned above has been resolved?
