### ISSUE TITLE
is "description" field a duplicate of "summary"?

### ISSUE THREAD

**Issue by corentinmusard** [pelican-plugins/seo#30]
Is there a need to create the metadata field `description` while there is already `summary` in pelican ?

In pelican's docs, the description of `summary` is `Brief description of content for index pages`.

**Comment by MaevaBrunelles** [comment]
Hello,

No it's not a duplicate. As described in the Pelican doc, `Summary` metadata generates a `<meta name="summary" content="Short version for index and feeds" />`, contrary to the `Description` SEO metadata which generate a `<meta name="description" content="" />`.
