### ISSUE TITLE
Usage guidance needs to be improved!

### ISSUE THREAD

**Issue by salfaris** [pelican-plugins/seo#41]
I really love the project. But when I first started using it, I had problems getting it to work. I tried pip installing and it seemed like nothing happened since I couldn't import the plugin (maybe I used the wrong alias?). I ended up git cloning the repo into my plugins folder and then it finally worked. It would be very helpful for future new users if there is a better step-by-step guide on how to use it.

**Comment by MaevaBrunelles** [comment]
Hi @salfaris and thanks for your interest in my plugin :)

Can you detailed what you tried? Did you get any error message? Which Pelican version do you use? Why do you try to import the plugin?

Instructions in the `README` (pip install) should be sufficient with Pelican `^4.5` as documented [here](https://docs.getpelican.com/en/latest/plugins.html#how-to-use-plugins).

To give an example, if I create a new Pelican project and want to use the SEO plugin:

Install Pelican:
```shell
$ python -m pip install "pelican[markdown]" 
$ pelican --version
4.6.0
```

Install the SEO plugin:
```shell
$ python -m pip install pelican-seo
```

Create a simple Pelican project with:
```shell
$ pelican-quickstart
```

Then generate the content:
```shell
$ pelican content
CRITICAL: You must fill in SITEURL variable in pelicanconf.py to use SEO plugin.
```

The last error message shows that SEO plugin is detected by Pelican and can be used.

**Comment by MaevaBrunelles** [comment]
Closing this issue as no answer since one month. If you still encounter issues, you can reopen this one.
