### ISSUE TITLE
License for this plugin

### ISSUE THREAD

**Issue by patrickdung** [pelican-plugins/seo#49]
Hello, the plugin looks good.
Would you please place the project under a specific open source license?
Thanks.

**Comment by justinmayer** [comment]
Thanks for the kind words, Patrick. The project is already under a specific license (AGPL-3.0), as noted in the [`pyproject` file](https://github.com/pelican-plugins/seo/blob/master/pyproject.toml#L6).

That said, I made this fact a bit more visible by adding a license badge to the README via 623e467. Cheers! ✨

**Comment by patrickdung** [comment]
Thanks for reply, I see the badge now... It's easy to overlook it.

It's a suggestion:
If the file 'LICENSE' is put into the repo, GitHub would also show the license of this plugin in the 'About' section in the right hand side of the page.

**Comment by justinmayer** [comment]
Good to know. I don't relish the idea of duplicating LICENSE files everywhere when a single line in our configuration should suffice. I think GitHub should be smart enough to look for that line in the `pyproject.toml` file — in fact, PyPI already does exactly that (see **Meta** section in left side-bar on [PyPI entry page](https://pypi.org/project/pelican-seo/)). Perhaps GitHub will do the same someday.
