### ISSUE TITLE
Allow settings to be in pelicanconf.py?

### ISSUE THREAD

**Issue by jacobwilliams** [pelican-plugins/seo#52]
Would it be useful if the various settings (e.g., `SEO_REPORT`, etc.) were allowed to be set in the `pelicanconf.py` file? Currently to change these, you have to edit the `settings.py` file (see #51). I can try to work on this if you think it would be a good idea!

**Comment by MaevaBrunelles** [comment]
Hi @jacobwilliams,

I think it's definitively a good idea and it would be useful for Pelican users as most of the other plugin ask to set settings in `pelicanconf.py`. If SEO settings are not find in Pelican file, you can fallback on default SEO settings. Your contribution is most than welcome :)
