### ISSUE TITLE
Report says I am missing 'Page description' & 'Content title' in all articles

### ISSUE THREAD

**Issue by Kentoseth** [pelican-plugins/seo#57]
Example link:

https://www.kentoseth.com/posts/2022/apr/17/python-pelican-how-to-view-draft-content-on-a-website/

Metadata from article:

```
Title: Python Pelican: How to view draft content on a website
Tags: pelican, blog
Author: Mohamed H.
Summary: Finding draft content on Pelican, a static site generator written in the Python programming language.
```

There is no metadata info for the things being requested in the report: https://docs.getpelican.com/en/stable/content.html

How do we add these things to the article metadata? How much do they impact SEO with/without having them?

**Comment by MaevaBrunelles** [comment]
Did you read [this part](https://github.com/pelican-plugins/seo#seo-report ) of the README?

It explains how to add a page description and a content title.

**Comment by Kentoseth** [comment]
I see it now, but I don't think it was there before :eyes: 

What is the difference between `Description` and `Summary`?

**Comment by MaevaBrunelles** [comment]
> I see it now, but I don't think it was there before :eyes: 

Feel free to browse the commits historic and you'll discover that this part comes from initial commit.

> What is the difference between `Description` and `Summary`?

`Summary` is a Pelican metadata, while `Description` is a SEO plugin metadata to build the HTML meta description tag.

**Comment by Mestrace** [comment]
On the title thing, I got the same error when I use something like
```markdown
Title: my metadata title
```

If I do this then SEO report the problem resolved.
```markdown
Title: my metadata title

# My actual title
```

But that looks very silly because it displays two title, something like below. 

------
# My metadata title
Posted on xxxxx

# My actual title
