### ISSUE TITLE
Asking for SITEURL in pelicanconf.py

### ISSUE THREAD

**Issue by Kentoseth** [pelican-plugins/seo#58]
When adding settings for pelican-seo to pelicanconf.py, it gives an error:
```
Exception: You must fill in SITEURL variable in pelicanconf.py       __init__.py:566
           to use SEO plugin. 
```

But this will break the site for local testing, which uses `localhost`. If you add a SITEURL, `localhost` stops working for rendering the content locally.

**Comment by MaevaBrunelles** [comment]
With following the Pelican quickstart plus filling `SITEURL` for the SEO plugin, there is no conflict with the localhost.
Preview the site with `pelican --listen` and navigate to the localhost doesn't impact the fact that you filled `SITEURL`.

So can you give more informations on the issue you encounter?
