### ISSUE TITLE
Canonical URL generation ignores save_as metadata

### ISSUE THREAD

**Issue by kevingoldsmith** [pelican-plugins/seo#7]
One of my pages (home.md) has a save__as metadata as index.html on that page, the canonical URL given is for <site URL>/pages/<site-name>.html.

This should check what the correct page URL is.

**Comment by MaevaBrunelles** [comment]
Hi @kevingoldsmith,

Thanks for your interest and raising an issue!

Your problem is normally fixed, it'll be prodded in the same time as the fix for the issue #8. You can follow it for the resolution. I don't create a dedicated PR for this because you risk to encounter the same bug as #8 after.

**Comment by kevingoldsmith** [comment]
Awesome! I'll take a look at the fix when it goes in. Maybe next time I'll be able to propose a fix if I find an issue. Looking forward to using this.

**Comment by MaevaBrunelles** [comment]
Hi @kevingoldsmith,

Strategy change, I've finally made a PR for this issue. Are you able to clone the branch and test if it fixes the issue you encounter? If you prefer to use pip, you can normally do `pip install git+https://github.com/pelican-plugins/seo@fix-canonical-url-with-save-as-setting`

If it works, I'll merge the PR and will see to deploy the fix.

**Comment by kevingoldsmith** [comment]
Will try to test it this weekend. Thanks!

**Comment by kevingoldsmith** [comment]
Hello @MaevaBrunelles, sorry it took so long to report back, testing now with your fix and it now works correctly!
